export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const SHOW_ALERT = 'SHOW_ALERT';
export const CLEAN_ALERT = 'CLEAN_ALERT';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const AUTHENTICATED_USER = 'AUTHENTICATED_USER';
export const LOG_OUT = 'LOG_OUT';

export const UPLOAD_FILE = 'UPLOAD_FILE';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_ERROR = 'UPLOAD_FILE_ERROR';

export const CREATE_URL_SUCCESS = 'CREATE_LINK_SUCCESS';
export const CREATE_URL_ERROR = 'CREATE_LINK_ERROR';

export const CLEAN_STATE = 'CLEAN_STATE';

export const ADD_PASSWORD = 'ADD_PASSWORD';
export const ADD_DOWNLOADS = 'ADD_DOWNLOADS';